server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  include /etc/nginx/mime.types;

  location = /parent/sw.js {
    add_header Cache-Control "no-cache";
    add_header Service-Worker-Allowed "/parent/";
    default_type application/javascript;
    try_files /parent/sw.js =404;
  }

  location /parent {
    try_files $uri $uri/ /parent/index.html;
  }

  location / {
    return 302 /parent/;
  }
}
